### ISSUE TITLE
Travis CI Failing at `build_cbi_cache.py`

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/WOFpy#135]
It appears that Travis CI is failing at https://travis-ci.org/ODM2/WOFpy/jobs/237613666#L638

when trying to run `build_cbi_cache.py` getting this error: 

lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

---

From @emiliom : My hunch is that it's best to move the cbi test (`test_cbi_parser.py`?) to the set of tests that don't cause TravisCI failures. But @ocefpaf is probably traveling right now.

The [test fails when](https://travis-ci.org/ODM2/WOFpy/jobs/237613666#L660) looking at file `/tmp/cbi_parameter_file.xml`, which appears to be a cached file. But that location seems odd.

We don't care much about the cbi test right now. So, we can look at it again when Filipe is back. Can you open a new targeted issue with the info you have here, plus what I've pasted? Thanks!

**Comment by lsetiawan** [comment]
This is what's in `/tmp/cbi_parameter_file.xml`

```
{"names":["property","value"],"values":[]}
```

> But that location seems odd.

The location is set as `CBI_CACHE_DIR = tempfile.gettempdir()`

**Comment by ocefpaf** [comment]
BTW this is the error message:

```shell
Traceback (most recent call last):
  File "wof/examples/flask/cbi/build_cbi_cache.py", line 435, in <module>
    param_names, LOCAL_PARAMETER_FILE_PATH)
  File "wof/examples/flask/cbi/build_cbi_cache.py", line 333, in parse_parameter_file
    tree = etree.parse(param_file)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81117)
  File "src/lxml/parser.pxi", line 1832, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118116)
  File "src/lxml/parser.pxi", line 1852, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:118399)
  File "src/lxml/parser.pxi", line 1747, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:117187)
  File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:111914)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
  File "/tmp/cbi_parameter_file.xml", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

I am investigating this now...

**Comment by ocefpaf** [comment]
@emiliom can you check if anything changed upstream with those responsible for http://mmisw.org/ont?form=rdf&uri=http://mmisw.org/ont/gcoos/parameter ? I don't have access to any cached past result but I am convinced that the breakage is due to a change in the `gcoos` service used in the test.

**Comment by emiliom** [comment]
Thanks for that detective work. As a matter of fact, I have here at the EarthCube meeting the best possible person to answer that question! Also, I do know that there was a version upgrade around May 26 to the mmisw.org/ont system.

For reference (for me at least):
- https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/cbi/build_cbi_cache.py#L21
- https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/cbi/build_cbi_cache.py#L435

*Tentatively*, I suspect the url should be replaced with http://mmisw.org/ont/api/v0/ont?format=rdf&iri=http://mmisw.org/ont/gcoos/parameter

But more generally, we should move this test out of the MANIFEST.IN (or in? I forget!) if we have problems that are not trivial.

**Comment by emiliom** [comment]
Went ahead and made that change (since it's a one liner) as [a commit](https://github.com/ODM2/WOFpy/commit/3bac69239b53379ef8f716a51f2e9120db1654df). We'll let the CI try it out

**Comment by ocefpaf** [comment]
Well, I already had a PR with that in https://github.com/ODM2/WOFpy/pull/137

**Comment by emiliom** [comment]
> Well, I already had a PR with that in #137

Yeah, I saw that ... We have really slow wifi here.

> (direct commits to the master branch are 😈)

I know. But it was a one liner, with the promise of near-immediate confirmation. And wifi here is terrible

Looks like it worked!!
