### ISSUE TITLE
No module named MySQLdb from the latest wofpy installation

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/WOFpy#151]
@ocefpaf I am still getting error when trying to deploy mysql database with the latest WOFpy due to missing `mysql-python` library...

ERROR:

```python
...
ImportError: No module named MySQLdb
Exception AttributeError: "'Odm2Dao' object has no attribute 'db_session'" in <bound method Odm2Dao.__del__ of 
...
```

From the installation, it seems like `mysql-python` is missing. 

```bash
$ conda create -n test -c odm2 python=2.7 wofpy
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/ubuntu/miniconda/envs/test:

The following NEW packages will be INSTALLED:

    attrs:             15.2.0-py27_0          
    automat:           0.5.0-py27_0           
    backports:         1.0-py27_0             
    click:             6.7-py27_0             
    configparser:      3.5.0-py27_0           
    constantly:        15.1.0-py27_0          
    django:            1.11.3-py27_0          
    docopt:            0.6.2-py27_0           
    flask:             0.12.2-py27_0          
    geoalchemy-odm2:   0.7.4-py27_0       odm2
    geos:              3.5.0-0                
    hyperlink:         17.1.1-py27_0          
    incremental:       16.10.1-py27_0         
    itsdangerous:      0.24-py27_0            
    jinja2:            2.9.6-py27_0           
    libiconv:          1.14-0                 
    libpq:             9.5.4-0                
    libsodium:         1.0.10-0               
    libxml2:           2.9.4-0                
    libxslt:           1.1.29-0               
    lxml:              3.8.0-py27_0           
    markupsafe:        0.23-py27_2            
    mkl:               2017.0.3-0             
    msgpack-python:    0.4.8-py27_0           
    nose:              1.3.7-py27_1           
    numpy:             1.13.0-py27_0          
    odm2api:           0.6.0.a0-py27_0    odm2
    openssl:           1.0.2l-0               
    pandas:            0.20.2-np113py27_0     
    pastedeploy:       1.5.2-py27_1           
    pcre:              8.39-1                 
    pip:               9.0.1-py27_1           
    psycopg2:          2.6.2-py27_2       odm2
    pymysql:           0.7.9-py27_0           
    pyodbc:            4.0.17-py27_0          
    pyparsing:         2.1.4-py27_0           
    pyramid:           1.5.7-py27_0           
    python:            2.7.13-0               
    python-dateutil:   2.6.0-py27_0       odm2
    pytz:              2017.2-py27_0          
    pyyaml:            3.12-py27_0            
    pyzmq:             16.0.2-py27_0          
    readline:          6.2-2                  
    repoze.lru:        0.6-py27_0             
    requests:          2.14.2-py27_0          
    setuptools:        27.2.0-py27_0          
    shapely:           1.5.17-np113py27_1 odm2
    simplejson:        3.10.0-py27_0          
    six:               1.10.0-py27_0          
    spyne:             2.12.14-py27_1     odm2
    sqlalchemy:        1.1.7-py27_0       odm2
    sqlite:            3.13.0-0               
    suds-jurko:        0.6-py27_0         odm2
    tk:                8.5.18-0               
    translationstring: 1.3-py27_0             
    twisted:           17.5.0-py27_0          
    unixodbc:          2.3.4-0                
    uwsgi:             2.0.15-py27_0      odm2
    venusian:          1.0-py27_0             
    webob:             1.4.1-py27_0           
    werkzeug:          0.12.2-py27_0          
    wheel:             0.29.0-py27_0          
    wofpy:             2.1.0b0-py27_0     odm2
    yaml:              0.1.6-0                
    zeromq:            4.1.5-0                
    zlib:              1.2.8-3                
    zope:              1.0-py27_0             
    zope.deprecation:  4.1.2-py27_1           
    zope.interface:    4.1.2-py27_1           

```

**Comment by emiliom** [comment]
@lsetiawan, there are at least two common Python MySQLl packages: `mysql-python` and `pymysql`. In most ODM2 work, or at least in `odm2api`, `pymysql` is used. In our NANOOS & vizer work, we use `mysql-python` exclusively. The latter is the one that has a `MySQLdb` importable module.

I don't remember what `wofpy` uses. Ideally it should be the same as `odm2api`. There's no reason to have to require both mysql libraries, at least in an ODM2 ecosystem. (BTW, I'm not aware if one is broadly considered "better" or better maintained than the other).

**Comment by emiliom** [comment]
Forgot to add: in your env, `mysql-python` is missing, but `pymysql` is present.

**Comment by lsetiawan** [comment]
Hmm..

```python
Traceback (most recent call last):
  File "runserver_odm2_timeseries.py", line 41, in <module>
    dao = Odm2Dao(get_connection(args.config))
  File "/home/ubuntu/miniconda/envs/wofpy/lib/python2.7/site-packages/wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py", line 24, in __init__
    convert_unicode=True,
  File "/home/ubuntu/miniconda/envs/wofpy/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/wofpy/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/ubuntu/miniconda/envs/wofpy/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 110, in dbapi
    return __import__('MySQLdb')
ImportError: No module named MySQLdb
```

From the traceback error, it seems like `sqlalchemy` is the one that uses `mysql-python`. So I'm not sure what's going on here.

**Comment by emiliom** [comment]
Hmm. You got me. Either something has changed, or I'm wrong about `pymysql` and `odm2api`! :(

**Comment by lsetiawan** [comment]
I found the problem. It seems that the problem lies within my connection string.

`odm2api` defaults using `pymysql` to build the connection string, this is why it works. I on the other hand uses `mysqldb` for wofpy. So I have to change the connection string to use `pymysql` to make things work.

`mysql+pymysql://user:***@127.0.0.1:3306/ODM2` instead of `mysql+mysqldb://user:***@127.0.0.1:3306/ODM2`

**Comment by emiliom** [comment]
Great! Sounds like an easy solution.

**Comment by lsetiawan** [comment]
Yepp. I applied the changes. It works. Thanks!

**Comment by emiliom** [comment]
Great. Let's make sure we catch that in the documentation, too.

**Comment by ocefpaf** [comment]
> @ocefpaf I am still getting error when trying to deploy mysql database with the latest WOFpy due to missing mysql-python library...

If you want to use `mysql-python` instead we can add it as a "server" dependency or something similar.
