### ISSUE TITLE
WaterOne Flow 1_1 get values breaks with 1.0 DAO 

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#18]
Catch unimplemented errors from 1.0 DAO to allow for basic 1.1 output.

Document attribute a minimal DOA to get basic WOF 1_0 and WOF 1_1 (GetSites, GetSiteInfo, GetVariables (work), and Getvalues)

Be sure the basic 1.0 DAO code will produce 1.1 output for GetSites, SiteInfo, Variables (work), and values. (breaking for csv example)

test with CSV example (Don't enhance DOA, unless absolutely necessary).

====
```
Traceback (most recent call last):
  File "C:\Users\valentin\venv_odm\lib\site-packages\spyne\application.py", line 151, in process_request
    ctx.out_object = self.call_wrapper(ctx)
  File "C:\Users\valentin\venv_odm\lib\site-packages\spyne\application.py", line 235, in call_wrapper
    retval = ctx.descriptor.service_class.call_wrapper(ctx)
  File "C:\Users\valentin\venv_odm\lib\site-packages\spyne\service.py", line 209, in call_wrapper
    return ctx.function(ctx, *args)
  File "D:\dev_odm\WOFpy\wof\apps\spyned_1_1.py", line 184, in GetValues
    valuesResult = WOFService.GetValuesObject(ctx,location,variable,startDate,endDate)
  File "D:\dev_odm\WOFpy\wof\apps\spyned_1_1.py", line 180, in GetValuesObject
    raise Fault(faultstring=str(inst))
Fault: Fault(Server: 'get_qualcontrollvls_by_ids Method not implemented.')
INFO:werkzeug:127.0.0.1 - - [30/Oct/2015 11:35:58] "GET /TxRivers/rest/1_1/GetValues?location=TxRivers:Austin&variable=TxRivers:Discharge_cfs HTTP/1.1" 500 -
```

**Comment by valentinedwv** [comment]
Closed
